# prompt_template: >
#   Please help me to translate the following text from a manga to {to_lang}
#   (if it's already in {to_lang} or looks like gibberish you have to output it as it is instead):\n

# temperature: 0.5

# top_p: 1

# chat_system_template: >
#   You are a professional translation engine, 
#   please translate the story into a colloquial, 
#   elegant and fluent content, 
#   without referencing machine translations. 
#   You must only translate the story, never interpret it.
#   If there is any issue in the text, output it as is.

#   Translate to {to_lang}.

# chat_sample:
#   日本語-简体中文:
#     - <|1|>恥ずかしい… 目立ちたくない… 私が消えたい…
#       <|2|>きみ… 大丈夫⁉
#       <|3|>なんだこいつ 空気読めて ないのか…？
#       <|4|>二人のちゅーを 目撃した ぼっちちゃん
#       <|5|>ふたりさん
#       <|6|>大好きなお友達には あいさつ代わりに ちゅーするんだって
#       <|7|>アイス あげた
#       <|8|>喜多ちゃんとは どどど どういった ご関係なのでしようか...
#       <|9|>テレビで見た！
#     - <|1|>好尴尬…我不想引人注目…我想消失…
#       <|2|>你…没事吧⁉
#       <|3|>这家伙怎么看不懂气氛的…？
#       <|4|>小孤独目击了两人的接吻
#       <|5|>二里酱
#       <|6|>我听说人们会把亲吻作为与喜爱的朋友打招呼的方式
#       <|7|>我给了她冰激凌
#       <|8|>喜多酱和你是怎么样的关系啊...
#       <|9|>我在电视上看到的！

# gpt4:
#   temperature: 0.5
{
  "gpt_config": {
    "prompt_template": "Please help me to translate the following text from a manga to {to_lang} (if it's already in {to_lang} or looks like gibberish you have to output it as it is instead):\n",
    "temperature": 0.5,
    "top_p": 1,
    "chat_system_template": "You are a professional translation engine, please translate the story into colloquial, elegant, and fluent content, without referencing machine translations. You must only translate the story, never interpret it. If there is any issue in the text, output it as is.\n\nTranslate to {to_lang}.",
    "chat_sample": {
      "日本語-简体中文": [
        "恥ずかしい… 目立ちたくない… 私が消えたい…",
        "きみ… 大丈夫⁉",
        "なんだこいつ 空気読めて ないのか…？",
        "二人のちゅーを 目撃した ぼっちちゃん",
        "ふたりさん",
        "大好きなお友達には あいさつ代わりに ちゅーするんだって",
        "アイス あげた",
        "喜多ちゃんとは どどど どういった ご関係なのでしようか...",
        "テレビで見た！"
      ],
      "中文": [
        "好尴尬…我不想引人注目…我想消失…",
        "你…没事吧⁉",
        "这家伙怎么看不懂气氛的…？",
        "小孤独目击了两人的接吻",
        "二里酱",
        "我听说人们会把亲吻作为与喜爱的朋友打招呼的方式",
        "我给了她冰激凌",
        "喜多酱和你是怎么样的关系啊...",
        "我在电视上看到的！"
      ]
    },
    "gpt4": {
      "temperature": 0.5
    }
  }
}
